### ISSUE TITLE
Bitwise OR calls bitwise AND internally

### ISSUE THREAD

**Issue by ioreskovic** [patrickfav/bytes-java#5] opened 2018-07-13 07:51 UTC
https://github.com/patrickfav/bytes-java/blob/53187bea8485cd6a717bbb6ea6df1808316e8661/src/main/java/at/favre/lib/bytes/Bytes.java#L710

**Comment by patrickfav** [comment] 2018-07-13 10:07
Hi Ivan, thanks for the report.

This is a duplicate of #2 and will be release 0.5.0 shortly.

**Closed by patrickfav** 2018-07-13 10:07 UTC
Labels: bug, duplicate
